# 注意　これを定期実行するのは、全てが安定動作することを確認してから！
# その時に他の個別の定期実行を切って手動実行のみにするのを忘れずに！

name: Every hour ALL run

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 * * * *'

jobs:
  IPA:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Python Install
          run: |
            python -m pip install --upgrade pip
            pip install Misskey.py
            pip install feedparser

        - name: Create Note&WP Content
          env:
            MISSKEY_SERVER_ADDRESS: ${{ secrets.MISSKEY_SERVER_ADDRESS }}
            MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
            WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
            WORDPRESS_API_PASSWORD: ${{ secrets.WORDPRESS_API_PASSWORD }}


          run: |
            python nvnb-ipa.py
            cat nvnb-ipa.txt

        - name: Update File
          run: |
            if ! git diff --exit-code --quiet
            then
             git add --update
              git config --global user.name ${{ secrets.YOUSER_NAME }}
              git config --global user.email ${{ secrets.MAIL_ADDRESS }}
              git commit -m "Update Content"
              git push
            fi
          
  JVN:
      runs-on: ubuntu-latest
      needs: IPA
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Python Install
          run: |
            python -m pip install --upgrade pip
            pip install Misskey.py
            pip install feedparser

        - name: Create Note&WP Content
          env:
            MISSKEY_SERVER_ADDRESS: ${{ secrets.MISSKEY_SERVER_ADDRESS }}
            MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
            WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
            WORDPRESS_API_PASSWORD: ${{ secrets.WORDPRESS_API_PASSWORD }}


          run: |
            python nvnb-jvn.py
            cat nvnb-jvn.txt

        - name: Update File
          run: |
            if ! git diff --exit-code --quiet
            then
             git add --update
              git config --global user.name ${{ secrets.YOUSER_NAME }}
              git config --global user.email ${{ secrets.MAIL_ADDRESS }}
              git commit -m "Update Content"
              git push
            fi
            
  JVN-iPedia:
      runs-on: ubuntu-latest
      needs: JVN
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Python Install
          run: |
            python -m pip install --upgrade pip
            pip install Misskey.py
            pip install feedparser

        - name: Create Note&WP Content
          env:
            MISSKEY_SERVER_ADDRESS: ${{ secrets.MISSKEY_SERVER_ADDRESS }}
            MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
            WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
            WORDPRESS_API_PASSWORD: ${{ secrets.WORDPRESS_API_PASSWORD }}


          run: |
            python nvnb-jvn-ipedia.py
            cat nvnb-jvn-ipedia.txt

        - name: Update File
          run: |
            if ! git diff --exit-code --quiet
            then
             git add --update
              git config --global user.name ${{ secrets.YOUSER_NAME }}
              git config --global user.email ${{ secrets.MAIL_ADDRESS }}
              git commit -m "Update Content"
              git push
            fi

